
services:
  syncthing:
    image: lscr.io/linuxserver/syncthing:latest
    container_name: syncthing_server
    hostname: amanth-hl-ubuntu
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8384:8384" # Web UI
      - "22002:22000/tcp" # TCP file transfers
      - "22002:22000/udp" # QUIC file transfers
      - "21027:21027/udp" # Local discovery
    volumes:
      - ./config:/config
      - /mnt/hdd-wd/amanth/phone_backup:/data/phone_backup
